/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package source;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CadastrarAlunos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName());

    /**
     * Creates new form CadastrarAlunos
     */
    public char SexoEscolhido;
    private List<Aluno> listaAlunos;
    private Arquivo arquivo = new Arquivo("alunos");
    
    public CadastrarAlunos() {
        initComponents();
        listaAlunos = arquivo.leArquivo();
        carregarTabelaInicial();
    }
    
    private void carregarTabelaInicial() {
        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        for (Aluno aluno : listaAlunos) {
            modelo.addRow(new Object[]{
                aluno.getNome(), aluno.getNascimento(), aluno.getSexo(),
                aluno.getMatricula(), aluno.getCurso(), aluno.getCPF(),
                aluno.getEndereco(), aluno.getEstado(), aluno.getTelefone()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        txtNome = new javax.swing.JTextField();
        txtNascimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        radMasculino = new javax.swing.JRadioButton();
        radFeminino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.addActionListener(this::txtNomeActionPerformed);

        jLabel1.setText("Nome Completo");

        jLabel2.setText("Data Nascimento");

        jLabel3.setText("Matricula");

        jLabel4.setText("Curso");

        Sexo.add(radMasculino);
        radMasculino.setText("Masculino");

        Sexo.add(radFeminino);
        radFeminino.setText("Feminino");

        jLabel5.setText("Sexo");

        jLabel6.setText("CPF");

        jLabel7.setText("Endereço completo (rua, número, bairro, cidade, CEP)");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        jLabel8.setText("Estado");

        jLabel9.setText("Telefone");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Data Nascimento", "Sexo", "Matricula", "Curso", "CPF", "Endereco ", "Estado", "Telefone"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurso)
                                    .addComponent(txtNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(radFeminino)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(183, 183, 183)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNascimento)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCPF))))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)))
                        .addGap(0, 308, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radMasculino)
                    .addComponent(radFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(radMasculino.isSelected()){  //se o sexo masculino for selecionado
           SexoEscolhido = 'M'; //salva o sexo masculino na variavel global
           JOptionPane.showMessageDialog(null, "Sexo Masculino Selecionado","ALERTA",JOptionPane.OK_OPTION);
           Aluno aluno = new Aluno( 
            txtNome.getText(),  //pega o texto do textField 
            txtNascimento.getText(),
            SexoEscolhido,  //decalrada uma variavel global em char para salvar o sexo selecionado
            txtMatricula.getText(),
            txtCurso.getText(),
            txtCPF.getText(),
            txtEndereco.getText(),
            String.valueOf(cmbEstado.getSelectedItem()),
            txtTelefone.getText()
           );
           // jTextArea1.append(aluno+";");    //faz aparecer no TextAREA
           
            listaAlunos.add(aluno);
            //cria o arquivo do objeto
            arquivo.gravaArquivo(); 
            
           //adiciona os itens na tabela
           javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) table.getModel();
           modelo.addRow(new Object[]{
               aluno.getNome(), aluno.getNascimento(), aluno.getSexo(),
               aluno.getMatricula(), aluno.getCurso(), aluno.getCPF(),
               aluno.getEndereco(), aluno.getEstado(),aluno.getTelefone()
           });
           
        }else if(radFeminino.isSelected()){ //se o sexo feminino for selecionado
            SexoEscolhido = 'F';    //salva o sexo feminino na variavel global
            JOptionPane.showMessageDialog(null, "Sexo Feminino selecionado","ALERTA",JOptionPane.OK_OPTION);
            Aluno aluno = new Aluno(
            txtNome.getText(),
            txtNascimento.getText(),
            SexoEscolhido,
            txtMatricula.getText(),
            txtCurso.getText(),
            txtCPF.getText(),
            txtEndereco.getText(),
            String.valueOf(cmbEstado.getSelectedItem()),
            txtTelefone.getText()
           );
            
            listaAlunos.add(aluno);
            //cria o arquivo do objeto
            arquivo.gravaArquivo();
           //jTextArea1.append(aluno+";"); //faz aparecer no TextAREA
           javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) table.getModel();
           modelo.addRow(new Object[]{
               aluno.getNome(), aluno.getNascimento(), aluno.getSexo(),
               aluno.getMatricula(), aluno.getCurso(), aluno.getCPF(),
               aluno.getEndereco(), aluno.getEstado(),aluno.getTelefone()
           });
        }

        
    }                                         

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int linhaSelecionada = table.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um aluno na tabela para excluir!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja excluir este aluno","Confirmação",JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION){
            listaAlunos.remove(linhaSelecionada);
            arquivo.gravaArquivo(); //atualiza o .TXT
        
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) table.getModel();
            modelo.removeRow(linhaSelecionada);
            
            JOptionPane.showMessageDialog(null, "Aluno excluído com sucesso!");
        }
    }                                          

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {                                   
        int linhaSelecionada = table.getSelectedRow();
        
        if (linhaSelecionada != -1) {
            Aluno a = listaAlunos.get(linhaSelecionada);
            
            txtNome.setText(a.getNome());
            txtNascimento.setText(a.getNascimento());
            txtMatricula.setText(a.getMatricula());
            txtCurso.setText(a.getCurso());
            txtCPF.setText(a.getCPF());
            txtEndereco.setText(a.getEndereco());
            cmbEstado.setSelectedItem(a.getEstado());
            txtTelefone.setText(a.getTelefone());
            
            if (a.getSexo() == 'M') {
                radMasculino.setSelected(true);
            } else {
                radFeminino.setSelected(true);
            }
        }
    }                                  

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int linhaSelecionada = table.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um aluno na tabela para editar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        char sexo;
        if (radMasculino.isSelected()) {
            sexo = 'M';
        } else if (radFeminino.isSelected()) {
            sexo = 'F';
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o sexo do aluno!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Aluno aluno = listaAlunos.get(linhaSelecionada);
        
        aluno.setNome(txtNome.getText());
        aluno.setNascimento(txtNascimento.getText());
        aluno.setSexo(sexo);
        aluno.setMatricula(txtMatricula.getText());
        aluno.setCurso(txtCurso.getText());
        aluno.setCPF(txtCPF.getText());
        aluno.setEndereco(txtEndereco.getText());
        aluno.setEstado(String.valueOf(cmbEstado.getSelectedItem()));
        aluno.setTelefone(txtTelefone.getText());
        
        arquivo.gravaArquivo(); // Salva as alterações no .txt
        
        // Atualiza visualmente na tabela
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) table.getModel();
        modelo.setValueAt(aluno.getNome(), linhaSelecionada, 0);
        modelo.setValueAt(aluno.getNascimento(), linhaSelecionada, 1);
        modelo.setValueAt(aluno.getSexo(), linhaSelecionada, 2);
        modelo.setValueAt(aluno.getMatricula(), linhaSelecionada, 3);
        modelo.setValueAt(aluno.getCurso(), linhaSelecionada, 4);
        modelo.setValueAt(aluno.getCPF(), linhaSelecionada, 5);
        modelo.setValueAt(aluno.getEndereco(), linhaSelecionada, 6);
        modelo.setValueAt(aluno.getEstado(), linhaSelecionada, 7);
        modelo.setValueAt(aluno.getTelefone(), linhaSelecionada, 8);
        
        JOptionPane.showMessageDialog(null, "Aluno alterado com sucesso!");
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarAlunos().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radFeminino;
    private javax.swing.JRadioButton radMasculino;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration                   
}
