/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author laboratorio
 */
public class Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form.class.getName());
    
    public char sexo;
    
    private Arquivo arquivo;
    private List<Pessoa> listaPessoas;
    private int linhaEdicao = -1;
    
    private void limparCampos() {
    txtNome.setText("");

    btnGrpSexo.clearSelection();

    chkEsporte.setSelected(false);
    chkTecnologia.setSelected(false);
    chkAstronomia.setSelected(false);

    cnbIdioma.setSelectedIndex(0);

    txtNome.requestFocus();
}
    
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        arquivo = new Arquivo("pessoas");
        listaPessoas = arquivo.leArquivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGrpSexo = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtNome = new javax.swing.JTextField();
        rdo_Feminino = new javax.swing.JRadioButton();
        rdo_Masculino = new javax.swing.JRadioButton();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPessoas = new javax.swing.JTextArea();
        lblInteresses = new javax.swing.JLabel();
        chkEsporte = new javax.swing.JCheckBox();
        chkAstronomia = new javax.swing.JCheckBox();
        chkTecnologia = new javax.swing.JCheckBox();
        cnbIdioma = new javax.swing.JComboBox<>();
        lblInteresses1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPessoas = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnGrpSexo.add(rdo_Feminino);
        rdo_Feminino.setText("Feminino");

        btnGrpSexo.add(rdo_Masculino);
        rdo_Masculino.setText("Masculino");
        rdo_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_MasculinoActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        lblSexo.setText("Sexo");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txaPessoas.setColumns(20);
        txaPessoas.setRows(5);
        jScrollPane1.setViewportView(txaPessoas);

        lblInteresses.setText("Interesses");

        chkEsporte.setText("Esporte");

        chkAstronomia.setText("Astronomia");

        chkTecnologia.setText("Tecnologia");

        cnbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espanhol", "Inglês", "Português" }));
        cnbIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnbIdiomaActionPerformed(evt);
            }
        });

        lblInteresses1.setText("Idioma");

        tblPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Idioma", "Tecnologia", "Astronomia", "Esporte"
            }
        ));
        jScrollPane2.setViewportView(tblPessoas);

        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblSexo)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_Masculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_Feminino)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInteresses)
                                    .addComponent(lblInteresses1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cnbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkEsporte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkTecnologia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkAstronomia))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEditar)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_Masculino)
                    .addComponent(rdo_Feminino)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInteresses)
                    .addComponent(chkEsporte)
                    .addComponent(chkTecnologia)
                    .addComponent(chkAstronomia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInteresses1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void rdo_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
    // 1. Validação do Nome
    if (txtNome.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite o nome!", "Alerta", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Validação do Sexo
    if (!rdo_Masculino.isSelected() && !rdo_Feminino.isSelected()) {
        JOptionPane.showMessageDialog(this, "Selecione um sexo!", "Alerta", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Coleta dos dados dos componentes
    char sexoSelecionado = rdo_Masculino.isSelected() ? 'M' : 'F';
    boolean tecnologia = chkTecnologia.isSelected();
    boolean astronomia = chkAstronomia.isSelected();
    boolean esportes = chkEsporte.isSelected();
    String idioma = String.valueOf(cnbIdioma.getSelectedItem());

    // 4. Criação do objeto Pessoa
    Pessoa p = new Pessoa(
        txtNome.getText().trim(),
        sexoSelecionado,
        idioma,
        tecnologia,
        astronomia,
        esportes
    );

    DefaultTableModel tabela = (DefaultTableModel) tblPessoas.getModel();

    // 5. Verificação: inserção de nova pessoa ou edição
    if (linhaEdicao == -1) {
        listaPessoas.add(p);
        tabela.addRow(p.obterDados()); // Adiciona a nova linha direto na JTable
    } else {
        listaPessoas.set(linhaEdicao, p);
        
        // Atualiza a linha existente na tabela visualmente
        Object[] dados = p.obterDados();
        for (int col = 0; col < dados.length; col++) {
            tabela.setValueAt(dados[col], linhaEdicao, col);
        }
        linhaEdicao = -1; // Reseta o estado de edição
    }

    // 6. Gravação e atualização visual
    arquivo.gravaArquivo();
    txaPessoas.append(p.toString() + "\n");

    JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
    limparCampos();
    }                                         

    private void cnbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int linha = tblPessoas.getSelectedRow();
        if (linha == -1){
            JOptionPane.showMessageDialog(
                    null,
                    "Selecoione uma pessoa na tabela.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente excluir esta pessoa",
                "confirmação",
                JOptionPane.YES_NO_OPTION
        );
        
        if (resposta == JOptionPane.YES_OPTION){
            listaPessoas.remove(linha);
            
            arquivo.gravaArquivo();
            
            DefaultTableModel tabela = (DefaultTableModel) tblPessoas.getModel();
            
            tabela.removeRow(linha);
            
            System.out.println("Pessoa Excluida");
        }
    }                                          

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int linha = tblPessoas.getSelectedRow();
        
        if (linha == -1){
            JOptionPane.showMessageDialog(
                    null,
                    "Selecione uma pessoa para editar"
            );
            return;
        }
        linhaEdicao = linha;
        Pessoa p = listaPessoas.get(linha);
        txtNome.setText(p.nome);
        if(p.sexo == 'M'){
           rdo_Masculino .setSelected(true);
        }else{
            rdo_Feminino .setSelected(true);
        }
        
        cnbIdioma.setSelectedItem(p.idioma);
    }                                         

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGrpSexo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkAstronomia;
    private javax.swing.JCheckBox chkEsporte;
    private javax.swing.JCheckBox chkTecnologia;
    private javax.swing.JComboBox<String> cnbIdioma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInteresses;
    private javax.swing.JLabel lblInteresses1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton rdo_Feminino;
    private javax.swing.JRadioButton rdo_Masculino;
    private javax.swing.JTable tblPessoas;
    private javax.swing.JTextArea txaPessoas;
    private javax.swing.JTextField txtNome;
    // End of variables declaration                   
}
