/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package source;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CadastroEspecie extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroEspecie.class.getName());

    /**
     * Creates new form CadastroEspecie
     */
    String SexoEscolhido;
    private List<Especie> listaEspecie;
    private ArquivoEspecie arquivo = new ArquivoEspecie("Especie");
    
    public CadastroEspecie() {
        initComponents();
        listaEspecie = arquivo.leArquivo();
        carregarTabelaInicial();
    }
    
     private void carregarTabelaInicial(){
        DefaultTableModel modelo = (DefaultTableModel) tblEspecie.getModel();
        modelo.setRowCount(0);
        
        for (Especie especie : listaEspecie){
             modelo.addRow(new Object[]{
                especie.getNomeCientifico(),especie.getApelido(),especie.getPeso(),
                especie.getAltura(),especie.getGrupo(),especie.getSexo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btngrpSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radMasculino = new javax.swing.JRadioButton();
        radFeminino = new javax.swing.JRadioButton();
        radErmafrodita = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeCientifico = new javax.swing.JTextField();
        txtApelido = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbGrupo = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspecie = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome Ciêntifico");

        jLabel2.setText("Apelido");

        btngrpSexo.add(radMasculino);
        radMasculino.setText("Masculino");

        btngrpSexo.add(radFeminino);
        radFeminino.setText("Feminino");

        btngrpSexo.add(radErmafrodita);
        radErmafrodita.setText("Ermafrodita");

        jLabel3.setText("Peso");

        jLabel4.setText("Altura");

        txtNomeCientifico.addActionListener(this::txtNomeCientificoActionPerformed);

        jLabel5.setText("Sexo");

        cmbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " mamíferos", " aves", " répteis", " anfíbios", "peixes ", "insetos", " aracnídeos", " crustáceos", " moluscos ", "anelídeos", " cnidários", " equinodermos", " poríferos", "nematódeos" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        jLabel6.setText("Grupo");

        tblEspecie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome Ciêntifico", "Apelido", "Peso", "Altura", "Sexo", "Grupo"
            }
        ));
        tblEspecie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicker(evt);
            }
        });
        jScrollPane1.setViewportView(tblEspecie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNomeCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeso)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApelido)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAltura)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radFeminino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radErmafrodita))
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEditar))
                                    .addComponent(jLabel6)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radMasculino)
                    .addComponent(radFeminino)
                    .addComponent(radErmafrodita)
                    .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void txtNomeCientificoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void MouseClicker(java.awt.event.MouseEvent evt) {                              
         int linhaSelecionada = tblEspecie.getSelectedRow();
        
        if (linhaSelecionada != -1) {
            Especie especie = listaEspecie.get(linhaSelecionada);
            
            txtNomeCientifico.setText(especie.getNomeCientifico());
            txtApelido.setText(especie.getApelido());
            txtPeso.setText(String.valueOf(especie.getPeso()));
            txtAltura.setText(String.valueOf(especie.getAltura()));
            
            if (especie.getSexo() == "Masculino") {
                radMasculino.setSelected(true);
                SexoEscolhido = "Masculino";
            } else if (especie.getSexo() == "Masculino") {
                radFeminino.setSelected(true);
                SexoEscolhido = "Feminino";
            }else {
                radErmafrodita.setSelected(true);
                SexoEscolhido = "Ermafrodita";
            }
            
            cmbGrupo.setSelectedItem(especie.getGrupo());
        }
    }                             

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
       if(radMasculino.isSelected()){
           SexoEscolhido = "Masculino";
       }else if(radFeminino.isSelected()){
           SexoEscolhido = "Feminino";
       }else if(radErmafrodita.isSelected()){
           SexoEscolhido = "Ermafrodita";
       }
       
       Especie especie = new Especie(
            txtNomeCientifico.getText(),
            txtApelido.getText(),
            Float.parseFloat(txtAltura.getText()),
            Float.parseFloat(txtPeso.getText()),
            String.valueOf(cmbGrupo.getSelectedItem()),
            SexoEscolhido
       );
       
       listaEspecie.add(especie);
       arquivo.gravaArquivo();
       
       javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEspecie.getModel();
       modelo.addRow(new Object[]{
           especie.getNomeCientifico(),especie.getApelido(),especie.getPeso(),
           especie.getAltura(),especie.getGrupo(),especie.getSexo()
       });
    }                                         

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int linhaSelecionada = tblEspecie.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um aluno na tabela para excluir!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja excluir este aluno","Confirmação",JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION){
            listaEspecie.remove(linhaSelecionada);
            arquivo.gravaArquivo(); //atualiza o .TXT
        
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEspecie.getModel();
            modelo.removeRow(linhaSelecionada);
            
            JOptionPane.showMessageDialog(null, "Aluno excluído com sucesso!");
        }
    }                                          

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int linhaSelecionada = tblEspecie.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto na tabela para editar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       if(radMasculino.isSelected()){
           SexoEscolhido = "Masculino";
       }else if(radFeminino.isSelected()){
           SexoEscolhido = "Feminino";
       }else if(radErmafrodita.isSelected()){
           SexoEscolhido = "Ermafrodita";
       }
       
        
        Especie especie = listaEspecie.get(linhaSelecionada);
        
        especie.setNomeCientifico(txtNomeCientifico.getText());
        especie.setApelido(txtApelido.getText());
        especie.setAltura(Float.parseFloat(txtAltura.getText()));
        especie.setPeso(Float.parseFloat(txtPeso.getText()));
        especie.setSexo(SexoEscolhido);
        especie.setGrupo(String.valueOf(cmbGrupo.getSelectedItem()));
        
        arquivo.gravaArquivo(); // Atualiza o .txt
        
        // Atualiza visualmente na tabela
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEspecie.getModel();
        modelo.setValueAt(especie.getNomeCientifico(), linhaSelecionada, 0);
        modelo.setValueAt(especie.getApelido(), linhaSelecionada, 1);
        modelo.setValueAt(String.valueOf(especie.getAltura()), linhaSelecionada, 2);
        modelo.setValueAt(String.valueOf(especie.getPeso()), linhaSelecionada, 3);
        modelo.setValueAt(especie.getGrupo(), linhaSelecionada, 4);
        modelo.setValueAt(especie.getSexo(), linhaSelecionada, 5);
        
        JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroEspecie().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup btngrpSexo;
    private javax.swing.JComboBox<String> cmbGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radErmafrodita;
    private javax.swing.JRadioButton radFeminino;
    private javax.swing.JRadioButton radMasculino;
    private javax.swing.JTable tblEspecie;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtNomeCientifico;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration                   
}
