/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package source;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CadastroProdutos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroProdutos.class.getName());

    /**
     * Creates new form CadastroProdutos
     */
    public int AtivoSelecionado;
    private List<Produto> listaProduto;
    private ArquivoProduto arquivo = new ArquivoProduto("Produto");
    public CadastroProdutos() {
        initComponents();
        listaProduto = arquivo.leArquivo();
        carregarTabelaInicial();
    }
    
    private void carregarTabelaInicial(){
        DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
        modelo.setRowCount(0);
        
        for (Produto produto : listaProduto){
             modelo.addRow(new Object[]{
                produto.getNome(),produto.getCodigo(),produto.getPreco(),
                produto.getQuantidade(),produto.getAtivo(),produto.getFornecedor()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        grpAtivo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        radSim = new javax.swing.JCheckBox();
        radNao = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cmbFornecedor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Codigo");

        jLabel3.setText("Preço");

        jLabel4.setText("Quantidade");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        txtPreco.addActionListener(this::txtPrecoActionPerformed);

        grpAtivo.add(radSim);
        radSim.setText("Sim");
        radSim.addActionListener(this::radSimActionPerformed);

        grpAtivo.add(radNao);
        radNao.setText("Não");
        radNao.addActionListener(this::radNaoActionPerformed);

        jLabel5.setText("Ativo");

        cmbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambev", "Nestlé", "Coca-Cola", "Unilever", "M. Dias Branco", "P&G", "Frids", " " }));

        jLabel6.setText("Fornecedor");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Codigo", "Preço", "Quantidade", "Fornecedor", "Ativo"
            }
        ));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClicker(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addComponent(txtPreco)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtCodigo)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radNao))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEditar))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radSim)
                    .addComponent(radNao)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void radSimActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void radNaoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
            if (radSim.isSelected()){
                AtivoSelecionado = 1;
            }else if (radNao.isSelected()){
                AtivoSelecionado = 0;
            }
            
            Produto produto = new Produto(
                    txtNome.getText(),
                    txtCodigo.getText(),
                    Float.parseFloat(txtPreco.getText()),
                    Float.parseFloat(txtQuantidade.getText()),
                    AtivoSelecionado,
                    String.valueOf(cmbFornecedor.getSelectedItem())
             );
            
            listaProduto.add(produto);
            arquivo.gravaArquivo();
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblProduto.getModel();
            modelo.addRow(new Object[]{
                produto.getNome(),produto.getCodigo(),produto.getPreco(),
                produto.getQuantidade(),produto.getAtivo(),produto.getFornecedor()
            });
    }                                         

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
         int linhaSelecionada = tblProduto.getSelectedRow();
        
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um aluno na tabela para excluir!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja excluir este aluno","Confirmação",JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION){
            listaProduto.remove(linhaSelecionada);
            arquivo.gravaArquivo(); //atualiza o .TXT
        
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblProduto.getModel();
            modelo.removeRow(linhaSelecionada);
            
            JOptionPane.showMessageDialog(null, "Aluno excluído com sucesso!");
        }
    }                                          

    private void mouseClicker(java.awt.event.MouseEvent evt) {                              
       int linhaSelecionada = tblProduto.getSelectedRow();
        
        if (linhaSelecionada != -1) {
            Produto produto = listaProduto.get(linhaSelecionada);
            
            txtNome.setText(produto.getNome());
            txtCodigo.setText(produto.getCodigo());
            txtPreco.setText(String.valueOf(produto.getPreco()));
            txtQuantidade.setText(String.valueOf(produto.getQuantidade()));
            
            if (produto.getAtivo() == 1) {
                radSim.setSelected(true);
                AtivoSelecionado = 1;
            } else {
                radNao.setSelected(true);
                AtivoSelecionado = 0;
            }
            
            cmbFornecedor.setSelectedItem(produto.getFornecedor());
        }
    }                             

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
int linhaSelecionada = tblProduto.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto na tabela para editar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (radSim.isSelected()) {
            AtivoSelecionado = 1;
        } else if (radNao.isSelected()) {
            AtivoSelecionado = 0;
        }
        
        Produto produto = listaProduto.get(linhaSelecionada);
        
        produto.setNome(txtNome.getText());
        produto.setCodigo(txtCodigo.getText());
        produto.setPreco(Float.parseFloat(txtPreco.getText()));
        produto.setQuantidade(Float.parseFloat(txtQuantidade.getText()));
        produto.setAtivo(AtivoSelecionado);
        produto.setFornecedor(String.valueOf(cmbFornecedor.getSelectedItem()));
        
        arquivo.gravaArquivo(); // Atualiza o .txt
        
        // Atualiza visualmente na tabela
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblProduto.getModel();
        modelo.setValueAt(produto.getNome(), linhaSelecionada, 0);
        modelo.setValueAt(produto.getCodigo(), linhaSelecionada, 1);
        modelo.setValueAt(produto.getPreco(), linhaSelecionada, 2);
        modelo.setValueAt(produto.getQuantidade(), linhaSelecionada, 3);
        modelo.setValueAt(produto.getAtivo(), linhaSelecionada, 4);
        modelo.setValueAt(produto.getFornecedor(), linhaSelecionada, 5);
        
        JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroProdutos().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbFornecedor;
    private javax.swing.ButtonGroup grpAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox radNao;
    private javax.swing.JCheckBox radSim;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration                   
}
